public enum Account {}
public enum Board {}
public enum Friends {}
public enum Groups {}
public enum Likes {}
public enum Messages {}
public enum Newsfeed {}
public enum Photos {}
public enum Polls {}
public enum Server {}
public enum Status {}
public enum Users {}
public enum Utils {}
public enum Wall {}
